### PR TITLE
Recalculate menu order on insertion or deletion

### PR DESCRIPTION
**Pull request by petruchek**
New private method called reorder_menu_items() which is being called after any menu item is being deleted or new menu item is being added and it has explicitly set position.

Issue reported and briefly discussed here: https://github.com/wp-cli/wp-cli/issues/5047

### CODE REVIEW

**Comment by petruchek** [comment]
Hi there @schlessera

Any news on this PR being merged?

Thanks

**Comment by schlessera** [comment]
Hi @petruchek,

Yes, I'd like to move this forward. However, we'll need Behat tests for this first. Can you add tests to assert that the menu IDs are correctly modified?

Let me know if you need assistance with writing the tests!

**Comment by petruchek** [comment]
> Let me know if you need assistance with writing the tests!

@schlessera, thank you for your response. 

Could you please guide me a little, please?

I'm assuming I need to modify features/menu-item.feature. Is this correct?
Do you think I need to create a separate scenario? Or I should modify existing scenarios?

Thank you for your time (very much)

**Comment by schlessera** [comment]
@petruchek 

> I'm assuming I need to modify features/menu-item.feature. Is this correct?

Yes, that's the one to edit.

> Do you think I need to create a separate scenario? Or I should modify existing scenarios?

Please create a separate scenario. In the existing tests, you can already see how the position is being represented in the output lists, so it should be relatively straight-forward to copy one of the existing scenarios and adapt it to test this PR.

**Comment by petruchek** [comment]
> @petruchek
> 
> > I'm assuming I need to modify features/menu-item.feature. Is this correct?
> 
> Yes, that's the one to edit.
> 
> > Do you think I need to create a separate scenario? Or I should modify existing scenarios?
> 
> Please create a separate scenario. In the existing tests, you can already see how the position is being represented in the output lists, so it should be relatively straight-forward to copy one of the existing scenarios and adapt it to test this PR.

Hi there,

Is it something that still makes sense doing? Please let me know.

**Comment by schlessera** [comment]
Hey @petruchek,
Yes, this still makes sense.

**Comment by schlessera** [comment]
Thanks for the PR, @petruchek !

**Pull request merged**
