### PR TITLE
Check for `STDIN` if `--post_content` is used

### LINKED ISSUE #175: `wp post generate --post_content` hangs if there's no STDIN
Running `wp post generate --prompt` will hang if the user enters `Y` for the `--post_content` parameter. I guess it's expecting input from stdin for this parameter.

### PR DESCRIPTION
**Pull request by Mte90**
Closes #175

### CODE REVIEW

**Comment by Mte90** [comment]
Again I am not sure if needs behat tests :-)

**Comment by Mte90** [comment]
This seems that is working without any issues and the tests confirm.

**Comment by schlessera** [comment]
The code you wrote works, but the `has_stdin()` method is currently broken for some edge cases (one of them being Behat tests).

Related:
- https://github.com/wp-cli/entity-command/issues/194
- https://github.com/wp-cli/entity-command/issues/164

I'll merge this for now, but mark the Behat as `@broken`, as I still think it is an improvement either way.

**Comment by schlessera** [comment]
Thanks for the PR, @Mte90 , as well as for your patience! ;)

**Pull request merged**
