### PR TITLE
Exclude transient from list

### PR DESCRIPTION
**Pull request by BhargavBhandari90**
For: https://github.com/wp-cli/entity-command/issues/121

### CODE REVIEW

**Comment by schlessera** [comment]
Thanks for the PR, @BhargavBhandari90 !

Can you add another test that makes use of the flag you've added, to make sure transients are shown in that case?

**Comment by BhargavBhandari90** [comment]
@schlessera The test for `transient` flag is already available at here https://github.com/wp-cli/entity-command/blob/master/features/option-list.feature#L21

**Comment by BhargavBhandari90** [comment]
Hey @schlessera it's showing `  The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: Connection timed out  
`  at here. https://travis-ci.org/wp-cli/entity-command/jobs/324292393

I think build needs to be restarted again. Not sure about hat

**Comment by gitlost** [comment]
Restarted that for you...

**Comment by BhargavBhandari90** [comment]
Thanks @gitlost . It worked.

**Comment by BhargavBhandari90** [comment]
@schlessera Added a test.

**Comment by schlessera** [comment]
@BhargavBhandari90 I'm sorry, I only realized just now that you have used the wrong mechanism to include the default transient.

You shouldn't set the `$exclude` variable, because that will then override any `--exclude=<something>` parameter that a user might have provided.

Instead, you should change the logic in https://github.com/wp-cli/entity-command/blob/master/src/Option_Command.php#L280-L287 and provide a default value of `false` instead of `null`:

```php
$show_transients = Utils\get_flag_value( $assoc_args, 'transients', false );
if ( $show_transients ) {
	$transients_query = " AND option_name LIKE '\_transient\_%'
	OR option_name LIKE '\_site\_transient\_%'";
} else {
	$transients_query = " AND option_name NOT LIKE '\_transient\_%'
	AND option_name NOT LIKE '\_site\_transient\_%'";
}
```

**Comment by BhargavBhandari90** [comment]
@schlessera Oh !!! Got it. Will make the change in this weekend. Thanks.

**Comment by BhargavBhandari90** [comment]
Hey @gitlost again it's time out https://travis-ci.org/wp-cli/entity-command/builds/325780058?utm_source=github_status&utm_medium=notification

**Comment by BhargavBhandari90** [comment]
Sending new PR. I merged `master` and got other changes in my PR.

**Pull request closed without merging**
