### PR TITLE
Improve command descriptions; add Handbook links

### PR DESCRIPTION
**Pull request by hearvox**
Related: [/wp-cli/issues/4302](https://github.com/wp-cli/wp-cli/issues/4302)

Changes:
___
Improve 'wp comment' command description in:
https://github.com/wp-cli/entity-command/blob/master/src/Comment_Command.php
(Related: (wp-cli/wp-cli#4302)[https://github.com/wp-cli/wp-cli/issues/4302]))

Current description: Manage comments.

New description:
Creates, updates, deletes, and moderates comments.

___
https://github.com/wp-cli/entity-command/issues
Improve 'wp menu' command description in:
https://github.com/wp-cli/entity-command/blob/master/src/Menu_Command.php
Current description: List, create, assign, and delete menus.

New description:
Lists, creates, assigns, and deletes the active theme's navigation menus.

See the [Navigation Menus](https://developer.wordpress.org/themes/functionality/navigation-menus/) reference in the Theme Handbook.

___
Improve 'wp network' command description in:
(Note: This command has no description now: Don't think it has a truth-src file.
There's is for its subcommand:
https://github.com/wp-cli/entity-command/blob/master/src/Network_Meta_Command.php
Should we create Network_Command.php a file in the entity-command repo?)

Current description: (none)

New description:
Manages meta fields for multisite networks.

___
Improve 'wp option' command description in:
https://github.com/wp-cli/entity-command/blob/master/src/Option_Command.php

Current description: Manage options.

New description:
Retrieves and sets site options, including plugin and WordPress settings.

See the [Plugin Settings API](https://developer.wordpress.org/plugins/settings/settings-api/) and the 
[Theme Options](https://developer.wordpress.org/themes/customize-api/) for more information on adding customized options.

___
Improve 'wp posts' command description in:
https://github.com/wp-cli/entity-command/blob/master/src/Post_Command.php
Current description: Manage posts.

New description:
Manages posts, content, and meta.

___
Improve 'wp post-type' command description in:
https://github.com/wp-cli/entity-command/blob/master/src/Post_Type_Command.php
Current description: Manage post types.

New description:
Retrieves details on the site's registered post-types.

Get details on WordPress built-in and [custom post types](https://developer.wordpress.org/plugins/post-types/).

___
Improve 'wp site' command description in:
https://github.com/wp-cli/entity-command/blob/master/src/Site_Command.php
Current description: Perform site-wide operations.

New description:
Performs site-wide operations on a multisite install.

___
Improve 'wp taxonomy' command description in:
https://github.com/wp-cli/entity-command/blob/master/src/Taxonomy_Command.php 
Current description: Manage taxonomies.

New description:
Retrieves information about registered taxonomies.

See references for [built-in taxonomies](https://developer.wordpress.org/themes/basics/categories-tags-custom-taxonomies/) and [custom taxonomies](https://developer.wordpress.org/plugins/taxonomies/working-with-custom-taxonomies/).

___
Improve 'wp term' command description in:
https://github.com/wp-cli/entity-command/blob/master/src/Term_Command.php
Current description: Manage terms.

New description:
Manages taxonomy terms and term meta, including create, delete, and list.

See reference for [taxonomies and their terms](https://codex.wordpress.org/Taxonomies).

___
Improve 'wp user' command description in:
https://github.com/wp-cli/entity-command/blob/master/src/User_Command.php
Current description: Manage users.

New description:
Manages users, along with their roles, capabilities, and meta.

See references for [Roles and Capabilities](https://codex.wordpress.org/Roles_and_Capabilities)and [WP User class](https://codex.wordpress.org/Class_Reference/WP_User).

### CODE REVIEW

**Comment by hearvox** [comment]
@miya0001, I see what you're saying. Someone took a part of changes we submitted as Issues and, while we were waiting for discussion, made pull requests of them. From now on, maybe we'll skip the suggestion of submitting an Issue first and go right to the PR -- to avoid this confusion.

I think I understand what I need to do with `wp menu` but have no idea what this means (I'm not that git savvy):
>  can you revert changes for them?

**Comment by hearvox** [comment]
Come to think of it, I'm not really sure about what to do about `wp menu` either.
> The description for `wp menu` is already merged, please merge them from master.

Should I fork the repo again and submit a PR with the new command? Or is there something I should select when submitting the PR in those pulldown choices (where it says "base fork:"). Or, if this takes you too long to explain to me, maybe point me to an URL we're I can figure this out. thanks, bg

**Comment by miya0001** [comment]
> I see what you're saying. Someone took a part of changes we submitted as Issues and, while we were waiting for discussion, made pull requests of them. From now on, maybe we'll skip the suggestion of submitting an Issue first and go right to the PR -- to avoid this confusion.

Sure, I think so too. 👍

**Comment by miya0001** [comment]
> Should I fork the repo again and submit a PR with the new command?

I guess it is the easiest way. Please open new pull-request.
I will close this. 

Thanks.

**Comment by miya0001** [comment]
Ah, sorry I will merge #75 and #77.
Can you update after `git pull` and please send new pull-request.

Thanks!

**Comment by hearvox** [comment]
@miya0001, I understand. Thanks. I'll fork the repo agian with the merges, make my changes again, then submit a new PR. So the PR can be closed anytime. Thanks for your help. Almost there.

**Comment by hearvox** [comment]
BTW, will get to that later today, not right now.

**Pull request closed without merging**
